name: pintOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install make
      run: sudo apt-get update && sudo apt-get install make

    - name: Run make
      run:
        cd src/userprog/
        make
        make check
        make clean
