name: pintOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Install make
    #   run: sudo apt-get update && sudo apt-get install make

    - name: Move to the file
      run: cd src/userprog/

    - name: checking address
      run: ls

    - name: Make
      run: make

    - name: Check
      run: make check

    - name: Clean
      run: make clean
        
